[project]
name = 'Specialized-Medical-Equipment-Calibration'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.technician-certification]
path = 'contracts/technician-certification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
